package Modulo_Transferencias.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2-jbossorg-4
 * 2025-06-06T09:56:14.054-03:00
 * Generated source version: 3.5.2-jbossorg-4
 *
 */
@WebServiceClient(name = "BancoSOAPService",
                  wsdlLocation = "http://localhost:8080/BancoClienteMock/BancoSOAP?wsdl",
                  targetNamespace = "http://soap.ws.Interfaces/")
public class BancoSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.ws.Interfaces/", "BancoSOAPService");
    public final static QName BancoSOAPPort = new QName("http://soap.ws.Interfaces/", "BancoSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BancoClienteMock/BancoSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BancoSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BancoClienteMock/BancoSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BancoSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BancoSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BancoSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BancoSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BancoSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BancoSOAP
     */
    @WebEndpoint(name = "BancoSOAPPort")
    public BancoSOAP getBancoSOAPPort() {
        return super.getPort(BancoSOAPPort, BancoSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoSOAP
     */
    @WebEndpoint(name = "BancoSOAPPort")
    public BancoSOAP getBancoSOAPPort(WebServiceFeature... features) {
        return super.getPort(BancoSOAPPort, BancoSOAP.class, features);
    }

}
