package Modulo_Transferencias.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2-jbossorg-4
 * 2025-06-06T09:56:13.997-03:00
 * Generated source version: 3.5.2-jbossorg-4
 *
 */
@WebService(targetNamespace = "http://soap.ws.Interfaces/", name = "BancoSOAP")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BancoSOAP {

    @WebMethod
    @WebResult(name = "depositos", targetNamespace = "http://soap.ws.Interfaces/", partName = "depositos")
    public DepositoArray obtenerDepositos()
;

    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "http://soap.ws.Interfaces/", partName = "resultado")
    public Resultado procesarTransferencia(

        @WebParam(partName = "rut", name = "rut")
        java.lang.String rut,
        @WebParam(partName = "monto", name = "monto")
        double monto
    );
}
